-- 用户凭证关系表
CREATE TABLE
    TAB_USER_CREDENCE
    (
        CREDENCE_ID VARCHAR(32) NOT NULL,
        USER_ID VARCHAR(32) NOT NULL,
        AUTH_TYPE_CODE CHAR(8) NOT NULL,
        CREDENCE_EXP CHAR(19) NOT NULL,
        REMARK VARCHAR(255),
        ST TIMESTAMP,
        PRIMARY KEY (CREDENCE_ID)
    );

